# Generated by Django 3.1.7 on 2021-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'Merged')])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
